# HEX SDK

include ../../../../build.mk

SUBDIRS = tests

LIB = $(HEX_SDK_LIB_ARCHIVE)

LIB_SRCS = process.c control.c process_util.cpp

COMPILE_FOR_SHARED_LIB = 1

include $(HEX_MAKEDIR)/hex_sdk.mk

