# HEX SDK

include ../../../../build.mk

# FIXME: weird! pass only when V=1 is set
#SUBDIRS = tests

LIB = $(HEX_SDK_LIB_ARCHIVE)

LIB_SRCS = table.c

COMPILE_FOR_SHARED_LIB = 1

include $(HEX_MAKEDIR)/hex_sdk.mk


