# HEX SDK

include ../../../../build.mk

TESTS_LIBS = $(HEX_TRANSLATE_LIB) $(HEX_SDK_LIB)

test_module_03_EXTRA_SRCS = extra_module_03.cpp
test_command_02_EXTRA_SRCS = extra_command_02.cpp

CLEAN += test.settings

include $(HEX_MAKEDIR)/hex_sdk.mk

