name: Fast Forward Merge

on:
  pull_request_target:
    types:
      - labeled

jobs:
  merge:
    if: ${{ github.event.label.name == 'done' && github.event.pull_request.mergeable == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out PR Target Branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Merge
        env: 
          TOPIC_BRANCH: ${{ github.head_ref }}
        run: |
          git pull origin $TOPIC_BRANCH
          git checkout $TOPIC_BRANCH
          git checkout @{-1}
          git branch
          git merge --ff-only $TOPIC_BRANCH
          git push
